/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.blacklocus.gradle.debian;

import java.io.File;
import java.io.IOException;
import java.io.Writer;
import java.io.FileWriter;
import java.nio.file.Files;
import org.gradle.testkit.runner.GradleRunner;
import org.gradle.testkit.runner.BuildResult;
import org.gradle.testkit.runner.TaskOutcome;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 * A simple functional test for the 'com.blacklocus.gradle.debian' plugin.
 */
public class DebianPluginFunctionalTest {
    @Test public void canRunTask() throws IOException {
        // Setup the test build
        File projectDir = new File("build/functionalTest");
        Files.createDirectories(projectDir.toPath());
        writeString(new File(projectDir, "settings.gradle"), "");
        writeString(new File(projectDir, "build.gradle"),
            "plugins {" +
            "  id('com.blacklocus.gradle.debian')" +
            "}");

        // Run the build
        BuildResult result = GradleRunner.create()
            .withPluginClasspath()
            .withProjectDir(projectDir)
            .withArguments("help", "--task", "buildDeb")
            .forwardOutput()
            .build();

        // Verify the result
        assertTrue(result.getOutput().contains("buildDeb"));
        assertEquals(TaskOutcome.SUCCESS, result.task(":help").getOutcome());
    }

    private void writeString(File file, String string) throws IOException {
        try (Writer writer = new FileWriter(file)) {
            writer.write(string);
        }
    }
}
