#!/bin/sh -e

case "$1" in
    configure)
      if [ -z "$2" ]; then
        echo "After the package was installed."
      else
        echo "After the package was upgraded."
      fi
    ;;
    triggered)
      echo "After the package was triggered."
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;
    *)
      echo "postinst called with unknown argument \`$1'" >&2
      exit 1
    ;;
esac

exit 0