#!/bin/sh -e

case "$1" in
    remove)
      echo "Before the package is removed, e.g., "
      systemctl stop hello.service
    ;;
    upgrade)
      echo "Before an upgrade."
    ;;
    failed-upgrade)
      echo "If the above upgrade fails."
    ;;
    deconfigure)
      echo "Before package is deconfigured."
    ;;
    *)
      echo "prerm called with unknown argument \`$1'" >&2
      exit 1
    ;;
esac

exit 0
