#!/usr/bin/env bash

set -e

case "$1" in
  configure)
    if ! getent passwd blacklocus >/dev/null; then
      adduser --disabled-password --gecos "" blacklocus
    fi
  ;;
  abort-upgrade|abort-remove|abort-deconfigure)
  ;;
  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac

# fix dir permissions
mkdir -p /var/log/blacklocus
chown -R blacklocus:blacklocus /var/log/blacklocus
chown -R blacklocus:blacklocus /opt/blacklocus